name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build [release]
      run: cargo build --release --verbose
    - name: Build [debug]
      run: cargo build --verbose
    - name: Run tests [release]
      run: cargo test --release --verbose
    - name: Run tests [debug]
      run: cargo test --verbose
